server:
  port: 0

spring:
  application:
    name: price-catalogue-service
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.100.100:1521/nwi
    username: mis_kopie
    password: mis_kopie
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:811/eureka/